from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import checkout

def test_product(driver, produknya, ukurannya, warnanya):
    search = driver.find_element(By.ID,"search")
    time.sleep(1)
    search.send_keys(produknya)
    time.sleep(2)
    search.send_keys(Keys.ENTER)
    time.sleep(2)
    driver.find_element(By.LINK_TEXT,produknya).click()
    time.sleep(2)
    opsi = driver.find_element(By.CLASS_NAME,"swatch-opt")
    time.sleep(1)
    opsi.find_element(By.XPATH,"//div[@option-label='"+ukurannya+"']").click()
    time.sleep(1)
    opsi.find_element(By.XPATH,"//div[@option-label='"+warnanya+"']").click()
    time.sleep(1)
    driver.find_element(By.ID,"product-addtocart-button").click()

def test_checkout_1(driver):
    test_product(driver, checkout.inputan.product1, checkout.inputan.ukuran1, checkout.inputan.warna1)
    time.sleep(4)
    driver.find_element(By.CLASS_NAME,"minicart-wrapper").click()
    time.sleep(5)
    driver.find_element(By.ID,"top-cart-btn-checkout").click()
    time.sleep(3)

def test_checkout_2(driver):
    test_product(driver, checkout.inputan.product1, checkout.inputan.ukuran1, checkout.inputan.warna1)
    time.sleep(2)
    test_product(driver, checkout.inputan.product2, checkout.inputan.ukuran1, checkout.inputan.warna2)
    time.sleep(4)
    driver.find_element(By.CLASS_NAME,"minicart-wrapper").click()
    time.sleep(5)
    driver.find_element(By.ID,"top-cart-btn-checkout").click()
    time.sleep(3)

def test_isi_form(driver):
    test_checkout_2(driver)
    shipping = driver.find_element(By.ID,"checkout-step-shipping")
    time.sleep(3)
    shipping.find_element(By.ID,"customer-email").send_keys(checkout.inputan.email)
    time.sleep(3)
    shipping.find_element(By.XPATH,"//option[@data-title='"+checkout.inputan.Country+"']").click()
    time.sleep(3)
    shipping.find_element(By.XPATH,"//input[@name='firstname']").send_keys(checkout.inputan.First_Name)
    time.sleep(1)
    shipping.find_element(By.XPATH,"//input[@name='lastname']").send_keys(checkout.inputan.Last_Name)
    time.sleep(1)
    shipping.find_element(By.XPATH,"//input[@name='company']").send_keys(checkout.inputan.Company)
    time.sleep(1)
    shipping.find_element(By.XPATH,"//input[@name='street[0]']").send_keys(checkout.inputan.StreetAddress_1)
    time.sleep(1)
    shipping.find_element(By.XPATH,"//input[@name='street[1]']").send_keys(checkout.inputan.StreetAddress_2)
    time.sleep(1)
    shipping.find_element(By.XPATH,"//input[@name='street[2]']").send_keys(checkout.inputan.StreetAddress_3)
    time.sleep(1)
    shipping.find_element(By.XPATH,"//input[@name='city']").send_keys(checkout.inputan.City)
    time.sleep(1)
    shipping.find_element(By.XPATH,"//input[@name='region']").send_keys(checkout.inputan.Province)
    time.sleep(2)
    shipping.find_element(By.XPATH,"//input[@name='postcode']").send_keys(checkout.inputan.Zip_Code_valid)
    time.sleep(3)
    shipping.find_element(By.XPATH,"//input[@name='telephone']").send_keys(checkout.inputan.Phone_Number)
    time.sleep(6)
    shipping.find_element(By.XPATH,"//button[@data-role='opc-continue']").click()
    time.sleep(5)